###
@item=3
GET http://localhost:8000/predict/

###
POST  http://localhost:8000/predict
Content-Type: application/json

{
  "transactionSubtype": "BUY_REGULAR",
  "type": "APARTMENT",
  "subtype": "DUPLEX",
  "region": "Flanders",
  "province": "Antwerp",
  "floor": 5,
  "bedroomCount": 2,
  "netHabitableSurface": 125,
  "constructionYear": 2013,
  "facadeCount": 1,
  "floorCount": 5,
  "condition": "AS_NEW",
  "hasLift": 1,
  "kitchen": "HYPER_EQUIPPED",
  "hasGarden": 0,
  "gardenSurface": 0,
  "hasTerrace": 1,
  "terraceSurface": 20,
  "fireplaceExists": 0,
  "hasSwimmingPool": 0,
  "hasAirConditioning": 0,
  "bathroomCount": 1,
  "showerRoomCount": 1,
  "toiletCount": 2,
  "parkingCountIndoor": 0,
  "parkingCountOutdoor": 1,
  "primaryEnergyConsumptionPerSqm": 100,
  "epcScore": "A",
  "hasDoubleGlazing": 1
}
